### ISSUE TITLE
Section 1.1.6 command to install packages

### ISSUE THREAD

**Issue by ygao55** [SMAC-Group/ds#28]
I could not install the package "SMAC-Group/stat297" by the command in the book.
Error message: package ‘SMAC-Group/stat297’ is not available (for R version 3.6.2)

Searched the website, the following commands worked to install the package:
install.packages("remotes")
remotes::install_github("SMAC-Group/stat297")

Also I had to download and install the Rtools first before being able to run install.packages:
https://cran.rstudio.com/bin/windows/Rtools/

**Comment by samorso** [comment]
Thanks for your feedback! The approach we meant in <https://smac-group.github.io/ds/index.html#r-and-rstudio> is: first, install the `devtools` package; load the package `library(devtools)`; then you can install the `stat297` with the command `devtools::install_github("SMAC-Group/stat297")`. I agree the explanations need more clarity. We will improve on the explanations. Since you managed the installation, I marked it as **close**.
